# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to=b'')),
                ('slug', models.SlugField(editable=False)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
