# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='nuevoBlog/images-articles/'),
        ),
    ]
