# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoBlog', '0003_auto_20160216_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='nuevoBlog/static/images-articles/'),
        ),
    ]
